version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: tasq-pg
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=tasq
    volumes:
      - tasq_pg_data:/bitnami/postgresql
    ports:
      - "5432:5432"

volumes:
  tasq_pg_data: